name: CI Workflow

on:
  push:
    branches: [main,develop]
  pull_request:
    branches: [main,develop]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Usa la última versión disponible de la serie 20.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      - name: Run linter
        run: npm run lint
        env:
          CI: true
